---
sidebar: sidebar 
permalink: deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: 在您確認 ONTAP 檔案系統或檔案系統的建議 FSX 在某些情況下符合您的確切需求之後，您可以使用工作負載工廠在 AWS 環境中部署系統。 
---
= 為 ONTAP 檔案系統部署 VMware 工作負載建議的 FSX
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在您確認 ONTAP 檔案系統（或某些情況下的多個檔案系統）所建議的 FSX 符合您的確切需求之後，您可以使用工作負載工廠在 AWS 環境中部署系統。

視您新增至工作負載原廠帳戶的原則和權限而定，您可以使用工作負載原廠（使用讀取 / 寫入模式），完全部署適用於 ONTAP 檔案系統的 FSX 。如果您的權限較少（唯讀模式），或是沒有權限（基本模式），則需要使用 Codebox 的 CloudForformation 資訊，並在 AWS 中自行部署適用於 ONTAP 檔案系統的 FSX 。

.在 AWS 上部署至 VMware Cloud 的需求
* 您必須在 AWS 軟體定義資料中心（ SDDC ）版本 1.20 或更新版本上使用 VMware Cloud 、才能為 ONTAP 檔案系統部署 FSX 。
* 您不得將適用於 ONTAP 檔案系統的 FSX 部署在 SDDC 部署期間所使用的相同 VPC 中。您必須將其部署在新的 Amazon VPC 中、以啟用 VMware Cloud on AWS 與 Amazon FSX for NetApp ONTAP 整合。
* 您必須在與 SDDC 相同的 AWS 區域內部署適用於 ONTAP 檔案系統的 FSX 。


.步驟
. 在 * 審查計畫 * 頁面底部、選取 * 部署 * 、隨即顯示建立 ONTAP 檔案系統的 FSX 頁面。
+
定義適用於 ONTAP 檔案系統的 FSX 的大部分欄位都是根據您提供的資訊來完成、但您需要在此頁面中填寫一些欄位。

+
您可以使用「快速建立」或「進階建立」選項。進階建立提供數個額外的儲存參數、可供您自訂。 https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["瞭解這兩個選項的功能"]

. * AWS 認證 * ：選取或新增認證，以授予工作負載工廠直接為 ONTAP 檔案系統建立 FSX 所需的權限。您也可以從 Codebox 選取 CloudForgation 程式碼、然後在 AWS 中自行部署適用於 ONTAP 檔案系統的 FSX 。
. * 檔案系統名稱 * ：輸入您要用於此 ONTAP 檔案系統的 FSX 名稱。
. * 標記 * ：您也可以新增標記、將此 FSX 分類為 ONTAP 檔案系統。
. 在「網路與安全性」區段中、輸入下列資訊：
+
.. * 地區與 VPC* ：選取要部署 ONTAP 檔案系統之 FSX 的區域與 VPC 。
+
如果您要在 AWS 上部署到 VMware Cloud 、請務必將其部署在 VPC 上、而 VPC 與部署 VMware Cloud on AWS 的 VPC 不同。

.. * 安全性群組 * ：使用 * 進階建立 * 選項時、您可以為 ONTAP VPC 的 FSX 選取預設安全性群組、以便所有流量都能存取 ONTAP 檔案系統的 FSX 。
+
您可以新增傳入規則、限制其他 AWS 服務可以存取 ONTAP 檔案系統的 FSX 。這會封鎖開啟的服務數量。以下是最低連接埠和通訊協定：

+
[cols="15,10,55"]
|===
| 通訊協定 | 連接埠 | 目的 


| TCP、udp | 111 | Portmapper （用於協商 NFS 要求中使用的連接埠） 


| TCP、udp | 635 | NFS mountd （接收 NFS 掛載要求） 


| TCP、udp | 2049 | NFS 網路流量 


| TCP、udp | 4045 | 網路鎖定管理員（ NLM 、 lockd ）：處理鎖定要求。 


| TCP、udp | 4046 | 網路狀態監視器（ NSM 、 statd ） - 通知 NFS 用戶端伺服器重新開機以進行鎖定管理。 
|===
.. * 可用性區域 * ：選取可用性區域和子網路。
+
如果您想要避免因跨 AZ 流量而產生費用、則應選擇與部署 VMware SDDC 相同的可用性區域。

.. * 加密 * ：使用 * 進階建立 * 選項時、您可以從下拉式清單中選取 AWS 加密金鑰名稱。
.. * 資料存放區存取控制 * ：使用 * 進階 cre* 選項時、您可以選擇所有主機是否都能存取資料存放區、或是只有特定子網路上的某些 vSphere 叢集節點可以存取資料存放區。


. 在「檔案系統詳細資料」區段中、輸入下列資訊：
+
.. * ONTAP 認證 * ：輸入並確認 ONTAP 密碼。
.. * 儲存 VM 認證 * （僅限進階建立）：輸入並確認儲存 VM 密碼。密碼可能是此檔案系統的專屬密碼、您也可以使用為 ONTAP 認證輸入的相同密碼。


. 在 * 摘要 * 區段中、您可以檢視 VMware 移轉顧問根據您的資訊所設計的適用於 ONTAP 檔案系統和資料存放區組態的 FSX 。
. 選取 * 建立 * 來部署 ONTAP 檔案系統的 FSX 。此程序最多可能需要 2 小時。
+
或者、您也可以在 Codebox 視窗中選取 * 重新導向至 CloudForgi狀態 * 、以使用 CloudForgiation 堆疊建立檔案系統。

+
無論是哪種情況、您都可以監控 CloudForgation 的建立進度。



.結果
已部署適用於 ONTAP 檔案系統的 FSX 。
