---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: 登入NetApp Workload Factory 以存取 VMware 規劃中心。您可以手動建立 EVS 的部署計劃。 
---
= 手動建立 Amazon EVS 的部署計劃
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
登入NetApp Workload Factory 以造訪 VMware 規劃中心。從那裡，您可以手動建立根據您的需求自訂的 Amazon EVS 部署計劃或遷移計劃。

請注意，您必須擁有使用者名稱和密碼才能存取 Workload Factory。如果您沒有存取權限，請立即建立帳戶。查看說明 https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["請按這裡"]。



== 透過手動指定環境要求來建立部署計劃

您可以手動指定 Amazon Elastic VMware Service 中虛擬機器的要求，並使用自訂的 Amazon FSx for NetApp ONTAP 檔案系統作為外部資料儲存。

.需求
* 您必須擁有 Amazon Elastic VMware Service 訂閱。


.步驟
. 使用以下方式之一登入 Workload Factory https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["主控台體驗"^] 。
. 或者，如果您從 Workload Factory 控制台存取 Workload Factory，請從 VMware 工作負載磁貼中選擇 *VMware 規劃中心*，然後選擇 *VMware 規劃中心*。顯示 VMware 規劃中心。
. 選擇*手動建立 EVS 計劃*。
. 輸入您的 VM 環境的要求。
+
[NOTE]
====
請記住以下虛擬機器遷移效能要求和建議：

** 出於效能原因，建議 VM 庫存的最小儲存容量為 10TiB。
** Amazon Elastic VMware Service 資料儲存區需要最小吞吐量，具體取決於您為此部署指定所需的 IOPS 數量。
** 根據 FSx for ONTAP 檔案系統配置，Amazon Elastic VMware Service 環境需要最少數量的外部資料儲存才能達到最佳效能。


====
. 準備好後，選擇*審查計劃*來審查遷移計劃。
. 檢閱計畫。展開每個部分以查看計劃詳細資訊。
+
預設情況下，Workload Factory 將遷移計劃儲存到規劃中心。您可以在頁面頂部附近取消選擇此選項。

. 或者，當您對遷移計劃滿意時，您可以透過選擇*匯出計劃（PDF）*將計劃詳細資訊下載為 PDF 文件。
. 當您準備好配置部署計劃時，請選擇*配置*。


link:deploy-fsx-file-system-evs.html["為 ONTAP 檔案系統部署 VMware 工作負載建議的 FSX"]。
