---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 瞭解 VMware 移轉顧問工作負載工廠元件的新功能。 
---
= 適用於 VMware 的 BlueXP  工作負載工廠的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
瞭解 VMware Cloud 移轉顧問工作負載工廠元件的新功能。



== 2024 年 12 月 1 日



=== Amazon EC2 移轉顧問的改善

此版本的 BlueXP  工作負載工廠適用於 VMware ，可改善移轉顧問的體驗：

* * 資料收集 * ： BlueXP  工作負載工廠 for VMware 支援您在使用移轉顧問時，在特定期間內收集資料的能力。
* * 虛擬機器選擇 * ： BlueXP  VMware 工作負載工廠現在支援您選擇要納入移轉部署的虛擬機器。
* * 快速與進階體驗 * ：當您使用移轉顧問時，您現在可以選擇快速移轉體驗，使用 RVtooles ，或是使用移轉顧問資料收集器的進階體驗。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用移轉顧問為 Amazon EC2 建立部署計畫"]



== 2024 年 11 月 3 日



=== VMware 移轉顧問的資料減量比率有助於您

此版本的 VMware Workload Factory 提供資料減量比助理。資料減量比率助理可協助您在準備 AWS 雲端上線時、決定哪種比率最適合您的 VMware 庫存和儲存資產。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用移轉顧問為 Amazon EC2 建立部署計畫"]



== 2024 年 9 月 19 日



=== VMware 移轉顧問增強功能

此 VMware 工作負載工廠版本具備功能與穩定性強化功能，並可在使用 VMware 移轉顧問時匯入及匯出移轉計畫。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用移轉顧問為 Amazon EC2 建立部署計畫"]= 2024 年 9 月 1 日



=== 移轉至 Amazon EC2

VMware 的工作負載工廠現在支援使用 VMware 移轉顧問移轉至 Amazon EC2 。



== 2024 年 7 月 7 日



=== VMware 工作負載工廠的初始版本

初始版本包含使用 VMware 移轉顧問來分析內部部署 vSphere 環境中目前的虛擬機器組態、並制定計畫、將建議的虛擬機器配置部署到 AWS 上的 VMware Cloud 、並將 NetApp ONTAP 檔案系統的自訂 Amazon FSX 做為外部資料存放區。
